name: Java CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
        os: [windows-x86_64, linux-x86_64]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build
        run: mvn -Djavacpp.platform=${{ matrix.os }} clean package
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Masxinlingvonta Built For ${{ matrix.os }}
          path: "masxinlingvonta-cli/target/masxinlingvonta-cli-*.jar"